# Site settings
title: Pham Minh Hiep
SEOTitle: Personal blog
description: Welcome to my personal blog.
keyword: "jekyll, theme, blog, blog theme"
url: "https://phamminhhiepit2.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/header-avatar.jpeg" # the avatar showing on the homepage

# GitHub repository (if the site is hosted by GitHub)
repository: Renovamen/jekyll-theme-gungnir
repository_branch: main

# Theme style settings
theme_style:
  highlight: # "dark" (default), "light"
  alert: # "flat" (default), "modern"
  post_preview: # "image" (default), "text"
    # display post's featured image on homepage or not

# Markdown enhancements settings
math:
  enable:
    true # false (default), true
    # math rendering for all posts and keynotes
  engine: # "katex" (default), "mathjax"
    # only make sense when `math.engine: true`
chart: true # false (default), true
mermaid: true # false (default), true
emoji-plus: true # false (default), true

# CDN settings
cdn:
  source: # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable: # false (default), true
    # optimizing asset files via jsDelivr or not

# Publish posts or collection documents with a future date.
future: true

collections:
  experiences:
    output: true
  publications:
    output: true
  projects:
    output: true

# SNS settings
sns:
  RSS: true
  github_username: PhamMinhHiepIT2
  weibo_username:
  zhihu_username:
  twitter_username:
  facebook_username: hiep.phamminhhiep.9
  linkedin_username: pham-minh-hiep-a73837122
  email_address: phamhiep13122k@gmail.com

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN

# Gems
# you have to `bundle config set path 'vendor/bundle' && bundle install` before local preview
plugins:
  - jekyll-paginate
  - jemoji

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true # we use highlight.js for syntax highlighting, so we disable rouge here

# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-paw
    submenus:
      - title: Me
        font: fas fa-user-astronaut
        url: /about/
      - title: Theme
        font: fas fa-meteor
        url: /theme/
  - title: Archive
    font: fas fa-archive
    url: /archive/
  - title: Links
    font: fas fa-link
    url: /links/

# Comment settings
comment:
  provider: gitalk # false (default), "disqus", "gitalk", "valine"

  # Disqus settings
  disqus_username: renovamen

  # Gitalk settings
  # https://github.com/gitalk/gitalk
  gitalk:
    clientID: "faf464da633b08ff5317"
    clientSecret: "402324fc860894e5fcba6320fddbddd1ec7f5644"
    repo: gitalk-comments
    owner: This-is-an-Apple
    admin:
      - Renovamen
      - This-is-an-Apple

  # Valine settings
  # https://valine.js.org/
  valine:
    appID:
    appKey:

# Analytics settings
analytics:
  # Baidu Analytics
  ba_track_id: "" # [your baidu track id]

  # Google Analytics
  ga_track_id: "G-85QW3SQBZ1" # [your google track id]

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: true # default: false
